Repository KC3Kai/KC3Kai, pull requests merged in 2018-07, with the labels that each got.

#1877 Panel buttons to manually live reload meta
  src/assets/img/ui/cam1.png
  src/assets/img/ui/exportdeck.png
  src/assets/img/ui/mute-x.png
  src/assets/img/ui/mute.png
  src/assets/img/ui/reload_quests.png
  src/assets/img/ui/reload_quotes.png
  src/assets/img/ui/rengo.png
  src/library/injections/dmm_takeover.js
  src/library/modules/Service.js
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.html
  src/pages/devtools/themes/natsuiro/natsuiro.js
  src/pages/game/api.js
  src/pages/game/dmm.js
Labels: area:backend, area:interface, area:translation, status:review

#2591 Release 32.6.5
  package.json
  src/assets/img/ui/cam1.png
  src/assets/img/ui/exportdeck.png
  src/assets/img/ui/mute-x.png
  src/assets/img/ui/mute.png
  src/assets/img/ui/reload_quests.png
  src/assets/img/ui/reload_quotes.png
  src/assets/img/ui/rengo.png
  src/library/injections/dmm_takeover.js
  src/library/managers/ConfigManager.js
  src/library/modules/Service.js
  src/library/objects/Gear.js
  src/library/objects/Ship.js
  src/manifest.json
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.html
  src/pages/devtools/themes/natsuiro/natsuiro.js
  src/pages/game/api.js
  src/pages/game/dmm.js
  src/pages/strategy/tabs/fleet/fleet.css
  src/pages/strategy/tabs/fleet/fleet.html
  src/pages/strategy/tabs/fleet/fleet.js
  src/pages/strategy/themes/dark.css
  update
Labels: type:release

#2600 Air raid defense shotdown prelim calculation
  src/library/objects/LandBase.js
  src/pages/devtools/themes/natsuiro/natsuiro.js
Labels: area:interface, type:feature
