Repository KC3Kai/KC3Kai, pull requests merged in 2018-03, with the labels that each got.

#2486 Fix battle prediction bug for partial CF
  src/library/modules/BattlePrediction.js
  src/library/modules/BattlePrediction/phases/Kouku.js
  tests/library/modules/BattlePrediction/integration/BattlePrediction.js
  tests/library/modules/BattlePrediction/integration/Kouku.js
  tests/library/modules/BattlePrediction/integration/battleData.js
  tests/library/modules/BattlePrediction/phases/Kouku.js
Labels: status:review, type:bug

#2485 Allow to filter ship list by RegEx
  src/pages/strategy/tabs/ships/ships.js
Labels: status:review, type:enhancement

#2495 Changed TsunDB submission URL and Dev Info
  src/data/developers.json
  src/library/modules/TsunDBSubmission.js
Labels: type:update-adjustment

#2504 Add air battle to airraid mouseover
  src/pages/strategy/sortielogs.js
Labels: area:interface, status:review, type:enhancement

#2505 Akashi improvement panel activities
  src/assets/js/global.js
  src/library/managers/GearManager.js
  src/library/managers/PlayerManager.js
  src/library/modules/Kcsapi.js
  src/library/modules/Network.js
  src/library/modules/Translation.js
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.html
  src/pages/devtools/themes/natsuiro/natsuiro.js
Labels: area:backend, area:interface, status:review, type:feature
