Repository KC3Kai/KC3Kai, pull requests merged in 2018-05, with the labels that each got.

#2559 Add new language "Cantonese"
  src/data/settings.json
  src/library/modules/Translation.js
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/strategy/strategy.css
Labels: area:interface, area:translation

#2556 Add anti-installation (and imps) additive/multiplicative bonus calculation
  src/library/managers/GearManager.js
  src/library/objects/Ship.js
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.html
  src/pages/devtools/themes/natsuiro/natsuiro.js
Labels: area:interface, area:mechanics, status:review, type:enhancement

#2566 Update anti-installation modifiers
  src/library/managers/GearManager.js
  src/library/objects/Ship.js
  src/pages/devtools/themes/natsuiro/natsuiro.js
Labels: area:data, area:interface, status:review, type:enhancement
