Repository KC3Kai/KC3Kai, pull requests merged in 2018-10, with the labels that each got.

#2688 Release 33.3.3
  .jshintrc
  package.json
  src/library/modules/AntiAir.js
  src/library/modules/Kcsapi.js
  src/library/modules/TsunDBSubmission.js
  src/library/objects/Node.js
  src/library/objects/Ship.js
  src/library/objects/ShowcaseExporter.js
  src/manifest.json
  src/pages/devtools/themes/natsuiro/js/Shipbox.js
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.js
  src/pages/devtools/themes/plain/js/Shipbox.js
  src/pages/devtools/themes/plain/plain.js
  src/pages/strategy/tabs/fleet/fleet.js
  src/pages/strategy/tabs/locking/locking.css
  update
Labels: type:release

#2694 Display equip bonus if new equip has bonus or is synergy gear
  src/library/objects/Ship.js
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.html
  src/pages/devtools/themes/natsuiro/natsuiro.js
Labels: area:interface, type:enhancement

#2699 Update list of required ships
  src/data/ship_quests.json
Labels: area:data, type:update-adjustment
