Repository KC3Kai/KC3Kai, pull requests merged in 2019-08, with the labels that each got.

#2864 Release 34.0.0
  update
Labels: status:WIP, type:release

#2874 Moonlight - tall layout
  src/assets/img/ui/layout.png
  src/assets/img/ui/layout_compact.png
  src/assets/img/ui/layout_square.png
  src/assets/img/ui/layout_tall.png
  src/assets/img/ui/layout_wide.png
  src/assets/img/ui/wall_of_text.png
  src/library/managers/ConfigManager.js
  src/pages/devtools/themes/moonlight/moonlight.css
  src/pages/devtools/themes/moonlight/moonlight.html
  src/pages/devtools/themes/moonlight/moonlight.js
Labels: area:interface, status:review

#2873 Adding average level display on ship list page
  src/pages/strategy/tabs/ships/ships.css
  src/pages/strategy/tabs/ships/ships.html
  src/pages/strategy/tabs/ships/ships.js
Labels: area:interface, status:review, type:enhancement
