Repository KC3Kai/KC3Kai, pull requests merged in 2019-06, with the labels that each got.

#2827 Update PvP Friends class
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.js
Labels: area:interface, status:review, type:enhancement

#2830 Update WhoCallsTheFleet DB
  src/data/WhoCallsTheFleet_items.nedb
  src/data/WhoCallsTheFleet_ships.nedb
Labels: area:data, type:update-adjustment

#2833 Update OASW condition
  src/library/objects/Ship.js
Labels: area:mechanics, type:update-adjustment

#2835 Add voices and player fleets to TsunDB friendlyfleet
  src/library/modules/TsunDBSubmission.js
Labels: area:backend, type:enhancement

#2840 Natsuiro (troll): Display "Jervaited" image instead of regular drop icon
  src/assets/img/ui/jervaited.png
  src/pages/devtools/themes/natsuiro/natsuiro.js
  src/pages/strategy/sortielogs.js
Labels: area:interface, status:review
