Repository KC3Kai/KC3Kai, pull requests merged in 2020-01, with the labels that each got.

#2931 some new moonlight theme options
  src/data/settings.json
  src/library/managers/ConfigManager.js
  src/pages/devtools/themes/moonlight/moonlight.css
  src/pages/devtools/themes/moonlight/moonlight.html
  src/pages/devtools/themes/moonlight/moonlight.js
Labels: area:interface, status:review

#2930 Update Strategy Room
  src/assets/img/ui/alert.png
  src/pages/devtools/themes/natsuiro/natsuiro.css
  src/pages/devtools/themes/natsuiro/natsuiro.html
  src/pages/devtools/themes/natsuiro/natsuiro.js
  src/pages/strategy/shipgrid.js
  src/pages/strategy/tabs/locking/locking.js
  src/pages/strategy/tabs/ships/ships.js
Labels: status:review, type:enhancement

#2942 moonlight syncup with natsurio
  src/assets/img/ui/alertfairy.png
  src/assets/img/ui/alertfairytea.png
  src/assets/img/ui/fleet_single2.png
  src/assets/img/ui/rengo2.png
  src/assets/img/ui/rengo_surface2.png
  src/assets/img/ui/rengo_transport2.png
  src/pages/devtools/themes/moonlight/moonlight.css
  src/pages/devtools/themes/moonlight/moonlight.html
  src/pages/devtools/themes/moonlight/moonlight.js
  src/pages/devtools/themes/natsuiro/natsuiro.html
  src/pages/devtools/themes/natsuiro/natsuiro.js
Labels: area:interface

#2949 Release 34.3.2
  package.json
  src/library/objects/Gear.js
  src/manifest.json
  update
Labels: type:release
